# .travis.yml
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required

env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - BOOTSTRAP_LATEX=""
  matrix:
    - NOT_CRAN="true"
    - NOT_CRAN="false"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo mkdir -p /usr/lib/R/library
  - echo 'R_LIBS=/usr/lib/R/library:/usr/lib/R/site-library/' > ~/.Renviron
  - sudo chmod 2777 /usr/lib/R/library
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install data.table
  - ./travis-tool.sh github_package jimhester/covr@4cae287abde5e2cf0c3c73aedeaec4d902dfd3ed
  - ./travis-tool.sh github_package jimhester/lintr@a769c0b8be6740329d8d855f230e6ff3c31175c1
  - ./travis-tool.sh github_package hadley/devtools@c1db284c876beef5d098a91b7b54d1e27cde25b8
  - ./travis-tool.sh github_package hadley/testthat@b32ddfa4ae49e83f17b95cb06cbc34a7a3083bf0

install:
  - ./travis-tool.sh install_deps

script:
  - travis_wait ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
